# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        my_config:
            toolbar: basic # basic standard full

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
